---
abstract: 'use Class::XSAccessor to speed up Moose accessors'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Import::Into: 1.001000
  Test::Fatal: 0
  Test::Moose: 0
  Test::More: 0.96
  Test::Requires: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: MooseX::XSAccessor
name: MooseX-XSAccessor
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Class::XSAccessor: 1.16
  Moose: 2.0600
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=MooseX-XSAccessor
  homepage: https://metacpan.org/release/MooseX-XSAccessor
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/p5-moosex-xsaccessor
version: 0.001
